export const decisionCriticalEvidenceRegistryVersion = 'theta-decision-critical-evidence-registry-v1' as const;

export type EvidenceRequirement = 'HARD_REQUIRED_SAFETY' | 'REQUIRED_WHEN_APPLICABLE' | 'ECONOMIC_RANKING_FEATURE';

export interface DecisionCriticalEvidenceField {
  readonly field: string;
  readonly producer: string;
  readonly consumer: string;
  readonly unit: string;
  readonly states: readonly string[];
  readonly requirement: EvidenceRequirement;
  readonly safetyCritical: boolean;
  readonly paperRequired: boolean;
  readonly unknownBehavior: string;
  readonly persistence: string;
  readonly closureCondition: string;
}

const field = (value: DecisionCriticalEvidenceField): DecisionCriticalEvidenceField => Object.freeze(value);

export const decisionCriticalEvidenceFields: readonly DecisionCriticalEvidenceField[] = [
  field({field:'broker.accountStatus',producer:'Alpaca GET /v2/account',consumer:'Paper bootstrap and plan assembly',unit:'ENUM',states:['ACTIVE','RESTRICTED','UNKNOWN'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'BLOCK_NEW_RISK',persistence:'FusionSnapshot.accountState and broker reconciliation snapshot',closureCondition:'Fresh authenticated account row with parsed status'}),
  field({field:'broker.optionsCapability',producer:'Alpaca account options levels',consumer:'Paper plan assembly',unit:'LEVEL',states:['KNOWN','UNKNOWN','INVALID'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'BLOCK_OPTIONS_ACTION',persistence:'FusionSnapshot.accountState',closureCondition:'Fresh finite approved or trading level'}),
  field({field:'broker.buyingPower',producer:'Alpaca GET /v2/account',consumer:'Sizing and assignment capacity',unit:'USD',states:['KNOWN','UNKNOWN','INVALID','STALE'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'QUANTITY_ZERO',persistence:'FusionSnapshot.accountState and management evidence',closureCondition:'Fresh nonnegative broker amount'}),
  field({field:'broker.positions',producer:'Alpaca GET /v2/positions',consumer:'Reconciliation, concentration and lifecycle',unit:'POSITION_ROWS',states:['COMPLETE','PARTIAL','ERROR','UNKNOWN'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'BLOCK_NEW_RISK_AND_RECONCILE',persistence:'FusionSnapshot.positionState and broker reconciliation snapshot',closureCondition:'Authenticated complete collection for current cycle'}),
  field({field:'broker.openOrders',producer:'Alpaca GET /v2/orders?status=open',consumer:'Reconciliation and equivalent exposure gate',unit:'ORDER_ROWS',states:['COMPLETE','PARTIAL','ERROR','UNKNOWN'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'BLOCK_NEW_RISK_AND_RECONCILE',persistence:'FusionSnapshot.positionState and broker reconciliation snapshot',closureCondition:'Authenticated complete current order collection'}),
  field({field:'market.session',producer:'Alpaca clock and calendar',consumer:'Runtime and plan handoff',unit:'BOOLEAN_AND_TIMESTAMPS',states:['OPEN_CONFIRMED','CLOSED_CONFIRMED','UNCONFIRMED','ERROR'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'BLOCK_NEW_RISK',persistence:'FusionSnapshot.marketSession',closureCondition:'Clock and exchange calendar agree for decision session'}),
  field({field:'universe.activeTradeable',producer:'Alpaca assets',consumer:'Universe discovery',unit:'BOOLEAN',states:['KNOWN_TRUE','KNOWN_FALSE','UNKNOWN'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'EXCLUDE_SYMBOL',persistence:'Universe discovery receipt',closureCondition:'Parsed active and tradable flags'}),
  field({field:'universe.underlyingPrice',producer:'Alpaca IEX quote and bars',consumer:'Liquidity, lattice and moneyness',unit:'USD_PER_SHARE',states:['KNOWN','STALE','UNKNOWN','INVALID'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'EXCLUDE_SYMBOL',persistence:'FusionSnapshot source provenance and underlying features',closureCondition:'Fresh positive finite reference with lineage'}),
  field({field:'universe.optionability',producer:'Alpaca option contract discovery',consumer:'Universe discovery',unit:'BOOLEAN',states:['KNOWN_TRUE','KNOWN_FALSE','PARTIAL','ERROR'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'EXCLUDE_SYMBOL',persistence:'Universe funnel receipt',closureCondition:'Bounded complete contract query'}),
  field({field:'universe.unsupportedCorporateActionPending',producer:'Alpaca corporate-action positive producer plus CorporateActionPaperPolicy',consumer:'Paper entry safety policy',unit:'POLICY_STATE',states:['KNOWN_RELEVANT_ACTION_BLOCK','PAPER_BOOTSTRAP_LIMITED','QUALIFIED_CLEAR','PROVIDER_ERROR_BLOCK','QUERY_INCOMPLETE_BLOCK','NEGATIVE_ASSURANCE_UNKNOWN_BLOCK'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'BLOCK_UNLESS_VERSIONED_BOUNDED_PAPER_FALLBACK_CLEARS',persistence:'Corporate-action query/positive tables, FusionSnapshot, Paper plan receipt',closureCondition:'Typed corporate-action policy decision with immutable lineage'}),
  field({field:'universe.eventNear',producer:'CompanyEventPaperPolicy and MacroRiskEvidence',consumer:'Paper entry safety policy',unit:'POLICY_STATE',states:['KNOWN_NEAR_EARNINGS_BLOCK','KNOWN_AFTER_EXPIRY_CLEAR','FUND_NOT_APPLICABLE_CLEAR','MACRO_EVENT_BLOCK','COVERAGE_UNKNOWN_BLOCK'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'BLOCK_NEW_RISK',persistence:'FusionSnapshot eventState and Paper plan receipt',closureCondition:'Typed company and macro policy decision'}),
  field({field:'event.prospectiveKnownAt',producer:'Optionomics events and THETA first-observation clock',consumer:'Macro policy and PIT research',unit:'UTC_TIMESTAMP',states:['KNOWN','UNKNOWN','INVALID','NOT_APPLICABLE'],requirement:'REQUIRED_WHEN_APPLICABLE',safetyCritical:true,paperRequired:true,unknownBehavior:'EXCLUDE_EVENT_FROM_CLEARANCE',persistence:'market.optionomics_event_first_observation',closureCondition:'Provider-known or first-observed time is valid at decision'}),
  field({field:'event.earningsDistanceTradingSessions',producer:'Optionomics metrics earnings_in_sessions',consumer:'CompanyEventPaperPolicy',unit:'TRADING_SESSIONS',states:['KNOWN_POSITIVE_DISTANCE','UNKNOWN','INVALID','NOT_OBSERVED','NOT_APPLICABLE'],requirement:'REQUIRED_WHEN_APPLICABLE',safetyCritical:true,paperRequired:true,unknownBehavior:'BLOCK_OPERATING_COMPANY_ENTRY',persistence:'FusionSnapshot.eventState.earningsDistance and Paper plan receipt',closureCondition:'Strict integer with session and observation lineage, or qualified fund N/A'}),
  field({field:'event.earningsDistanceDays',producer:'RETIRED_UNSUPPORTED_CALENDAR_DAY_FIELD',consumer:'No Paper consumer',unit:'CALENDAR_DAYS',states:['RETIRED_NOT_APPLICABLE'],requirement:'REQUIRED_WHEN_APPLICABLE',safetyCritical:false,paperRequired:false,unknownBehavior:'NEVER_COERCE_FROM_TRADING_SESSIONS',persistence:'UNKNOWN register retirement receipt',closureCondition:'Paper policy consumes trading-session field instead'}),
  field({field:'event.macroFedCoverage',producer:'Optionomics bounded events coverage',consumer:'MacroRiskEvidence',unit:'BOUNDED_WINDOW',states:['COMPLETE','PARTIAL','ERROR','INVALID'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'BLOCK_NEW_RISK',persistence:'FusionSnapshot.eventState.macroFedCoverage',closureCondition:'Complete pagination and PIT-valid rows for governed horizon'}),
  field({field:'instrument.classification',producer:'Versioned manifest or positive company earnings evidence',consumer:'Company and corporate-action policies',unit:'ENUM',states:['OPERATING_COMPANY','NON_COMPANY_FUND','UNKNOWN','CONFLICT'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'BLOCK_NEW_RISK',persistence:'Paper plan safety receipt',closureCondition:'Production authority identifies class without research-label inference'}),
  field({field:'instrument.paperBootstrapApproved',producer:'Versioned owner-reviewed manifest',consumer:'CorporateActionPaperPolicy',unit:'BOOLEAN',states:['APPROVED','NOT_APPROVED','UNKNOWN'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'DISALLOW_PROVIDER_LIMITED_FALLBACK',persistence:'Source-controlled versioned manifest and Paper plan receipt',closureCondition:'Explicit approved entry with authority and effective time'}),
  field({field:'contract.identity',producer:'Alpaca option contracts',consumer:'Candidate construction and order handoff',unit:'OCC_IDENTITY',states:['KNOWN','UNKNOWN','INVALID','AMBIGUOUS'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'REJECT_CONTRACT',persistence:'market.option_contract and candidate evidence',closureCondition:'Exact OCC identity matches selected contract'}),
  field({field:'contract.tradable',producer:'Alpaca option contracts',consumer:'Candidate and corporate-action policy',unit:'BOOLEAN',states:['KNOWN_TRUE','KNOWN_FALSE','UNKNOWN'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'REJECT_CONTRACT',persistence:'Normalized contract and Paper policy receipt',closureCondition:'Provider flag is true'}),
  field({field:'contract.deliverable',producer:'Alpaca show_deliverables contract query',consumer:'CorporateActionPaperPolicy',unit:'CLASSIFICATION',states:['STANDARD_EQUITY','ADJUSTED','UNKNOWN'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'BLOCK_PROVIDER_LIMITED_FALLBACK',persistence:'Normalized contract and canonical frontier leg',closureCondition:'One ordinary equity deliverable matches underlying and multiplier'}),
  field({field:'contract.multiplier',producer:'Alpaca option contracts',consumer:'Economics, sizing and order construction',unit:'SHARES_PER_CONTRACT',states:['KNOWN','UNKNOWN','INVALID'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'REJECT_CONTRACT',persistence:'market.option_contract and canonical frontier',closureCondition:'Positive provider-derived integer, standard fallback requires 100'}),
  field({field:'contract.quoteBbo',producer:'Alpaca option snapshot and finalist refresh',consumer:'Executability, AEGIS and pricing',unit:'USD_PER_SHARE',states:['GOOD','STALE','MISSING','CROSSED','INVALID','ERROR'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'NON_EXECUTABLE',persistence:'market.option_quote_snapshot and FusionSnapshot',closureCondition:'Fresh two-sided exact-contract quote'}),
  field({field:'contract.spread',producer:'Normalized Alpaca BBO',consumer:'Executability and spread stress',unit:'DECIMAL_RATIO',states:['KNOWN','UNKNOWN','INVALID','TOO_WIDE'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'NON_EXECUTABLE',persistence:'Normalized contract and quote ledger',closureCondition:'Finite nonnegative spread within versioned bound'}),
  field({field:'contract.delta',producer:'Alpaca or exact Optionomics contract match',consumer:'Lattice and research cohorts',unit:'OPTION_DELTA',states:['KNOWN','UNKNOWN','INVALID'],requirement:'ECONOMIC_RANKING_FEATURE',safetyCritical:false,paperRequired:false,unknownBehavior:'KEEP_VISIBLE_WITH_UNCERTAINTY_UNLESS_BRANCH_REQUIRES',persistence:'Normalized contract and candidate evidence',closureCondition:'Strict finite value with feature-level provenance'}),
  field({field:'contract.iv',producer:'Alpaca or exact Optionomics contract match',consumer:'AEGIS IV and research ranking',unit:'DECIMAL_ANNUALIZED_VOLATILITY',states:['KNOWN','UNKNOWN','INVALID','STALE'],requirement:'REQUIRED_WHEN_APPLICABLE',safetyCritical:true,paperRequired:true,unknownBehavior:'AEGIS_HOLD_OR_COLD_START_POLICY',persistence:'Normalized contract and AEGIS assessment',closureCondition:'Current session strict finite IV with lineage'}),
  field({field:'aegis.tickerConcentrationPct',producer:'Candidate-inclusive account exposure',consumer:'AEGIS',unit:'DECIMAL_FRACTION',states:['KNOWN','UNKNOWN','NOT_APPLICABLE'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'HOLD_ONLY',persistence:'FusionSnapshot riskState and decision receipt',closureCondition:'Fresh account/position/candidate exposure derivation'}),
  field({field:'aegis.sectorConcentrationPct',producer:'Single-risk-group bootstrap proxy or future PIT sector source',consumer:'AEGIS',unit:'DECIMAL_FRACTION',states:['KNOWN','UNKNOWN','NOT_APPLICABLE'],requirement:'REQUIRED_WHEN_APPLICABLE',safetyCritical:true,paperRequired:true,unknownBehavior:'HOLD_ONLY_WHEN_APPLICABLE',persistence:'FusionSnapshot riskState',closureCondition:'Governed applicability plus real derivation'}),
  field({field:'aegis.correlationClusterExposurePct',producer:'Single-risk-group bootstrap proxy or PIT correlation producer',consumer:'AEGIS',unit:'DECIMAL_FRACTION',states:['KNOWN','UNKNOWN','NOT_APPLICABLE'],requirement:'REQUIRED_WHEN_APPLICABLE',safetyCritical:true,paperRequired:true,unknownBehavior:'HOLD_ONLY_WHEN_APPLICABLE',persistence:'FusionSnapshot riskState',closureCondition:'Governed applicability plus real derivation'}),
  field({field:'aegis.portfolioCapitalAtRiskPct',producer:'Candidate-inclusive account exposure',consumer:'AEGIS',unit:'DECIMAL_FRACTION',states:['KNOWN','UNKNOWN','INVALID'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'HOLD_ONLY',persistence:'FusionSnapshot riskState',closureCondition:'Fresh equity and downside exposure'}),
  field({field:'aegis.assignmentCapacityUsedPct',producer:'Broker buying power and secured collateral derivation',consumer:'AEGIS and sizing',unit:'DECIMAL_FRACTION',states:['KNOWN','UNKNOWN','NOT_APPLICABLE'],requirement:'REQUIRED_WHEN_APPLICABLE',safetyCritical:true,paperRequired:true,unknownBehavior:'HOLD_ONLY_OR_QUANTITY_ZERO',persistence:'FusionSnapshot riskState and management input',closureCondition:'Fresh broker evidence or governed N/A'}),
  field({field:'aegis.liquidityAcceptable',producer:'Candidate quote quality',consumer:'AEGIS liquidity family',unit:'BOOLEAN',states:['KNOWN_TRUE','KNOWN_FALSE','UNKNOWN'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'HOLD_ONLY',persistence:'FusionSnapshot riskState',closureCondition:'Fresh bid/ask and spread assessment'}),
  field({field:'aegis.executionQualityAcceptable',producer:'Execution quality contract',consumer:'AEGIS execution family',unit:'BOOLEAN',states:['KNOWN_TRUE','KNOWN_FALSE','UNKNOWN'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'HOLD_ONLY',persistence:'FusionSnapshot riskState',closureCondition:'Current quote and provider state qualify'}),
  field({field:'aegis.providerState',producer:'Provider evidence aggregate',consumer:'AEGIS provider family',unit:'ENUM',states:['OK','DEGRADED','ERROR','UNKNOWN'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'HOLD_ONLY',persistence:'FusionSnapshot source provenance',closureCondition:'All required current providers observed'}),
  field({field:'aegis.stressGapDetected',producer:'Alpaca PIT daily bars and current session',consumer:'AEGIS system family',unit:'BOOLEAN',states:['KNOWN_TRUE','KNOWN_FALSE','UNKNOWN','INVALID'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'HOLD_ONLY',persistence:'FusionSnapshot regime/risk state',closureCondition:'Session-confirmed current gap assessment'}),
  field({field:'aegis.stressIvShockDetected',producer:'Current contract IV plus PIT baseline',consumer:'AEGIS system family',unit:'BOOLEAN',states:['KNOWN_TRUE','KNOWN_FALSE','BASELINE_ACCUMULATING','STALE','INVALID','PROVIDER_ERROR'],requirement:'REQUIRED_WHEN_APPLICABLE',safetyCritical:true,paperRequired:true,unknownBehavior:'HOLD_ONLY_UNLESS_VERSIONED_COLD_START_NA',persistence:'AEGIS assessment and FusionSnapshot',closureCondition:'Current IV valid and detector ready or governed cold start'}),
  field({field:'aegis.stressSpreadWideningDetected',producer:'Current Alpaca BBO plus PIT spread cohort',consumer:'AEGIS liquidity/system families',unit:'BOOLEAN',states:['KNOWN_TRUE','KNOWN_FALSE','BASELINE_ACCUMULATING','STALE','INVALID','PROVIDER_ERROR'],requirement:'REQUIRED_WHEN_APPLICABLE',safetyCritical:true,paperRequired:true,unknownBehavior:'HOLD_ONLY_UNLESS_VERSIONED_COLD_START_NA',persistence:'AEGIS assessment and FusionSnapshot',closureCondition:'Current spread valid and detector ready or governed cold start'}),
  field({field:'sizing.collateralCapacity',producer:'Strike, multiplier, buying power and obligations',consumer:'Canonical sizing',unit:'WHOLE_CONTRACTS',states:['KNOWN','UNKNOWN','INVALID'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'QUANTITY_ZERO',persistence:'Candidate sizing receipt',closureCondition:'Fresh finite inputs produce nonnegative integer'}),
  field({field:'sizing.assignmentCapacityQty',producer:'Canonical broker buying-power/collateral derivation',consumer:'Entry and management frontiers',unit:'WHOLE_CONTRACTS',states:['KNOWN','UNKNOWN','NOT_APPLICABLE'],requirement:'REQUIRED_WHEN_APPLICABLE',safetyCritical:true,paperRequired:true,unknownBehavior:'QUANTITY_ZERO_OR_BLOCK_ASSIGNMENT',persistence:'Candidate and management evidence',closureCondition:'Fresh account evidence or lifecycle N/A'}),
  field({field:'sizing.selectedQty',producer:'Canonical constrained sizing',consumer:'Decision authority and plan assembly',unit:'WHOLE_CONTRACTS',states:['POSITIVE','ZERO_EXPLAINED','UNKNOWN_INVALID'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'NO_ACTION_PLAN',persistence:'Candidate, decision and action plan',closureCondition:'Integer quantity with binding constraint'}),
  field({field:'decision.aegisState',producer:'Python AEGIS over real-derived input',consumer:'Canonical frontier and Paper plan',unit:'ENUM',states:['ALLOW_FULL','ALLOW_REDUCED','HOLD_ONLY','HARD_VETO','UNKNOWN'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'SYSTEM_HOLD',persistence:'Decision receipt and action plan',closureCondition:'Candidate-bound assessment with DERIVED_FROM_REAL lineage'}),
  field({field:'decision.canonicalAction',producer:'Canonical strategy frontier',consumer:'Paper plan assembly',unit:'ENUM',states:['OPEN_CSP','GLOBAL_WAIT','SYSTEM_HOLD','MANAGEMENT_AUTHORITY'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'NO_ACTION_PLAN',persistence:'trade.decision',closureCondition:'All applicable authorized branches evaluated'}),
  field({field:'execution.preSubmitQuote',producer:'Exact-contract Alpaca refresh',consumer:'MasterPaperActionHandoff',unit:'TWO_SIDED_BBO',states:['QUALIFIED','MISSING','STALE','INVALID','ERROR'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'STOP_BEFORE_POST',persistence:'TCA execution event',closureCondition:'Fresh exact-contract quote at handoff'}),
  field({field:'reconciliation.quality',producer:'Broker reconciliation worker',consumer:'Runtime and corporate fallback',unit:'ENUM',states:['GOOD','DEGRADED','INVALID','UNKNOWN'],requirement:'HARD_REQUIRED_SAFETY',safetyCritical:true,paperRequired:true,unknownBehavior:'LOCK_NEW_RISK',persistence:'Broker reconciliation snapshot',closureCondition:'Current broker/local facts reconciled'}),
  field({field:'management.assignmentCapacity',producer:'Canonical broker capacity derivation',consumer:'Management action frontier',unit:'WHOLE_ASSIGNABLE_LOTS',states:['KNOWN_POSITIVE','KNOWN_ZERO','UNKNOWN','NOT_APPLICABLE'],requirement:'REQUIRED_WHEN_APPLICABLE',safetyCritical:true,paperRequired:false,unknownBehavior:'BLOCK_ACCEPT_ASSIGNMENT_ONLY',persistence:'Management input receipt',closureCondition:'Fresh broker evidence or lifecycle N/A'}),
  field({field:'management.candidateDiscovery',producer:'ProductionPaperManagementCandidateSource',consumer:'Paper bootstrap management frontier',unit:'CANDIDATE_ARRAYS_AND_STATE',states:['READY','VALID_EMPTY','PARTIAL_COVERAGE','PROVIDER_ERROR','STALE','NOT_ENTITLED','INVALID'],requirement:'REQUIRED_WHEN_APPLICABLE',safetyCritical:true,paperRequired:false,unknownBehavior:'BLOCK_ONLY_AFFECTED_MANAGEMENT_ACTION',persistence:'Management discovery receipt',closureCondition:'Typed candidate source result with reasons'}),
];

export function validateDecisionCriticalEvidenceRegistry(entries: readonly DecisionCriticalEvidenceField[] = decisionCriticalEvidenceFields): {
  readonly contractVersion: typeof decisionCriticalEvidenceRegistryVersion;
  readonly coverage: 'COMPLETE';
  readonly fieldCount: number;
} {
  if (entries.length === 0) throw new Error('DECISION_CRITICAL_EVIDENCE_REGISTRY_EMPTY');
  const seen = new Set<string>();
  for (const entry of entries) {
    if (seen.has(entry.field)) throw new Error(`DECISION_CRITICAL_EVIDENCE_DUPLICATE:${entry.field}`);
    seen.add(entry.field);
    if (!entry.producer || !entry.consumer || !entry.unit || entry.states.length === 0 || !entry.unknownBehavior
      || !entry.persistence || !entry.closureCondition) throw new Error(`DECISION_CRITICAL_EVIDENCE_INCOMPLETE:${entry.field}`);
    if (entry.paperRequired && !entry.safetyCritical) throw new Error(`PAPER_REQUIRED_FIELD_NOT_SAFETY_CRITICAL:${entry.field}`);
  }
  return { contractVersion: decisionCriticalEvidenceRegistryVersion, coverage: 'COMPLETE', fieldCount: entries.length };
}
